on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system packages
            sudo yum -y update

            # Install Node.js and npm (latest version)
            curl -sL https://rpm.nodesource.com/setup_20.x | sudo bash -
            sudo yum install -y nodejs

            # Navigate to the project directory
            cd /home/ec2-user/app/my-app

            # Install project dependencies
            npm install

            # Build the Next.js project
            npm run build

            # Install PM2 to keep the app running in the background
            sudo npm install -g pm2

            # Start the Next.js app with PM2
            pm2 start npm --name "nextjs-app" -- start

            # Save the PM2 process list so it persists after reboot
            pm2 save

            # Setup PM2 to restart on server reboot
            sudo pm2 startup systemd -u ec2-user --hp /home/ec2-user

            # Restart PM2 to apply the changes
            sudo systemctl restart pm2
