on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            # Add Node.js source for latest version
            curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            # Navigate to the project directory
            cd app/my-app
            # Install project dependencies
            npm install
            # Build the project
            npm run build
            # Clean up existing files in the web server directory
            sudo rm -rf /var/www/html/*
            # Move the build files to the web server directory
            sudo mv build/* /var/www/html
            # Set proper SELinux context for the web content (for CentOS/Fedora, not needed in Ubuntu)
            # sudo chcon -R -t httpd_sys_content_t /var/www/html
            # Restart Apache to apply changes
            sudo systemctl restart apache2
