on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            sudo apt-get update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            # Add Node.js source for latest version
            NODE_VERSION="20.x"
            curl -sL https://deb.nodesource.com/setup_${NODE_VERSION} | sudo -E bash -
            sudo apt-get install -y nodejs
            # Navigate to the project directory
            if [ -d "app/my-app" ]; then
              cd app/my-app
              npm install
              npm run build
            else
              echo "Directory app/my-app not found!"
              exit 1
            fi
            # Clean up existing files in the web server directory
            if [ ! -d "build" ]; then
              echo "Build directory not found! Exiting."
              exit 1
            fi
            sudo rm -rf /var/www/html/*
            sudo mv build/* /var/www/html
            # Restart Apache to apply changes
            sudo systemctl restart apache2
